---
resources:
- name: resource-src
  type: git
  source:
    uri: https://github.com/vponnam/concourse.git

jobs:
- name: multi-tasks
  public: true
  plan:
  - get: resource-src
    trigger: true
  - task: task1
    file: resource-src/task1.yml
    task: task2
    file: resource-src/task2.yml