---
resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/vponnam/concourse.git

jobs:
- name: test-pipeline1
  public: true
  plan:
  - get: git-resource
  - task: task1
    file: git-resource/task1.yml