---
platform: linux

resources:
- name: send-an-email
  type: email
  source:
    smtp:
      host: {{smtp-host}}
      port: {{smtp-port}} # this must be a string
      username: {{smtp-username}}
      password: {{smtp-password}}
    from: {{email-from}}
    to: [ {{email-to}} ]

inputs:
- get: src
- get: send-an-email

jobs:
- name: alert
  plan:
  - put: send-an-email
      params:
        subject: demo-prep-sha-email/generated-subject
        body: demo-prep-sha-email/generated-body

run:
  path: src/workout/email/email.sh

outputs:
- name: email-out

params:
  file_to_hash: email-resource/LICENSE
  output_subject_file: Concourse-task-status
  output_body_file: smoke-test
