---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.5"}

inputs:
- get: src
- get: email-resource-source

jobs:
- name: email-notification
  serial: true
  plan:
    config:
      params:
        file_to_hash: src/Dockerfile
        output_subject_file: Concourse-task-status
        output_body_file: smoke-test
  - put: send-email
    params:
      subject: email-out/Concourse-task-status
      body: email-out/smoke-test
run:
  path: src/workout/email/email.sh
outputs:
- name: email-out

params:
  file_to_hash: email-resource/LICENSE
  output_subject_file: Concourse-task-status
  output_body_file: smoke-test
